# Generated by Django 5.2.8 on 2025-11-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='is_lab',
            field=models.BooleanField(default=False, help_text='If checked, this subject is scheduled in 2 continuous periods (labs).'),
        ),
    ]
