# Generated by Django 5.2.8 on 2025-11-29 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_classsubject_is_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Primary teacher for this subject in this class (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='timetable.teacher'),
        ),
    ]
