# Generated by Django 5.2.8 on 2025-11-29 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_classsubject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Primary teacher for this subject in this class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='timetable.teacher'),
        ),
    ]
